services:

  mysql:
    image: mysql:8.0
    container_name: careeriq-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - careeriq-network


  redis:
    image: redis:7-alpine
    container_name: careeriq-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - careeriq-network



volumes:

  mysql_data:



networks:

  careeriq-network:
    driver: bridge